#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

function() {
  local fb_prompt_file=/opt/facebook/share/scm-prompt
  if [ -f "$fb_prompt_file" ]; then
    source "$fb_prompt_file"
  fi
  fb_prompt_file="${ADMIN_SCRIPTS}/scm-prompt"
  if [ -f "$fb_prompt_file" ]; then
    source "$fb_prompt_file"
  fi
}

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

fpath+=~/.zsh
autoload -Uz manydots-magic
manydots-magic
autoload -Uz match-llvm-clang

bindkey $terminfo[kcuu1] up-line-or-search
bindkey $terminfo[kcud1] down-line-or-search
bindkey "^R" history-incremental-search-backward

export EDITOR='vim'
export VISUAL='vim'

export KEYTIMEOUT=1
zstyle ':prezto:module:editor:info:keymap:alternate' format '%F{009}N%f'
zstyle ':prezto:module:editor:info:keymap:primary' format '%F{010}I%f'

export PATH=~/devtools:$PATH
export LSCOLORS=Gxfxcxdxbxegedabagacad

setopt interactivecomments

# source local zshrc
[[ ! -f ~/.zshrh.local ]] && source ~/.zshrc.local
